In [ ]:
mc cp s3/projet-slums-detection/data-prediction/PLEIADES/MAYOTTE/2020/predictions.gpkg pred_mayotte_2020.gpkg 
mc cp s3/projet-slums-detection/data-prediction/PLEIADES/MAYOTTE/2023/predictions.gpkg pred_mayotte_2023.gpkg

In [2]:
import geopandas as gpd

# Assurez-vous que vos GeoDataFrames sont chargés, par exemple :
gdf1 = gpd.read_file('pred_mayotte_2020.gpkg')
gdf2 = gpd.read_file('pred_mayotte_2023.gpkg')

In [12]:
intersections

,filename,id,geometry
0,projet-slums-detection/data-raw/PLEIADES/MAYOT...,0,"POLYGON ((502750.000 8601881.500, 502750.000 8..."
1,projet-slums-detection/data-raw/PLEIADES/MAYOT...,1,"POLYGON ((502763.500 8601876.500, 502767.000 8..."
2,projet-slums-detection/data-raw/PLEIADES/MAYOT...,2,"POLYGON ((502942.500 8601801.000, 502944.500 8..."
3,projet-slums-detection/data-raw/PLEIADES/MAYOT...,0,"POLYGON ((503125.000 8601640.500, 503125.000 8..."
4,projet-slums-detection/data-raw/PLEIADES/MAYOT...,0,"POLYGON ((504614.500 8601625.000, 504614.500 8..."
...,...,...,...
28096,projet-slums-detection/data-raw/PLEIADES/MAYOT...,1,"POLYGON ((517500.000 8574750.000, 517500.000 8..."
28097,projet-slums-detection/data-raw/PLEIADES/MAYOT...,2,"POLYGON ((517330.000 8574743.500, 517332.000 8..."
28098,projet-slums-detection/data-raw/PLEIADES/MAYOT...,3,"POLYGON ((517725.500 8574250.000, 517725.500 8..."
28099,projet-slums-detection/data-raw/PLEIADES/MAYOT...,0,"POLYGON ((521955.500 8589451.000, 521958.000 8..."
28100,projet-slums-detection/data-raw/PLEIADES/MAYOT...,1,"POLYGON ((521795.000 8589053.500, 521799.500 8..."

In [29]:
intersections_left

,filename_left,id_left,geometry,index_right,filename_right,id_right
10,projet-slums-detection/data-raw/PLEIADES/MAYOT...,10,"POLYGON ((502750.000 8601877.000, 502750.000 8...",0,projet-slums-detection/data-raw/PLEIADES/MAYOT...,0
11,projet-slums-detection/data-raw/PLEIADES/MAYOT...,11,"POLYGON ((502761.000 8601878.500, 502763.500 8...",1,projet-slums-detection/data-raw/PLEIADES/MAYOT...,1
22,projet-slums-detection/data-raw/PLEIADES/MAYOT...,8,"POLYGON ((503125.000 8601656.000, 503125.500 8...",3,projet-slums-detection/data-raw/PLEIADES/MAYOT...,0
26,projet-slums-detection/data-raw/PLEIADES/MAYOT...,1,"POLYGON ((505736.500 8591733.000, 505741.000 8...",40,projet-slums-detection/data-raw/PLEIADES/MAYOT...,1
32,projet-slums-detection/data-raw/PLEIADES/MAYOT...,0,"POLYGON ((505838.000 8593960.000, 505841.500 8...",42,projet-slums-detection/data-raw/PLEIADES/MAYOT...,1
...,...,...,...,...,...,...
26885,projet-slums-detection/data-raw/PLEIADES/MAYOT...,2,"POLYGON ((513083.500 8578482.500, 513084.500 8...",8175,projet-slums-detection/data-raw/PLEIADES/MAYOT...,2
26885,projet-slums-detection/data-raw/PLEIADES/MAYOT...,2,"POLYGON ((513083.500 8578482.500, 513084.500 8...",8174,projet-slums-detection/data-raw/PLEIADES/MAYOT...,1
26886,projet-slums-detection/data-raw/PLEIADES/MAYOT...,0,"POLYGON ((524007.000 8586000.000, 524023.500 8...",22556,projet-slums-detection/data-raw/PLEIADES/MAYOT...,3
26886,projet-slums-detection/data-raw/PLEIADES/MAYOT...,0,"POLYGON ((524007.000 8586000.000, 524023.500 8...",20683,projet-slums-detection/data-raw/PLEIADES/MAYOT...,23
26886,projet-slums-detection/data-raw/PLEIADES/MAYOT...,0,"POLYGON ((524007.000 8586000.000, 524023.500 8...",22861,projet-slums-detection/data-raw/PLEIADES/MAYOT...,304

In [24]:

# Effectuer une jointure spatiale pour identifier les polygones qui s'intersectent
# Nous utilisons 'predicate="intersects"' pour obtenir uniquement les paires qui s'intersectent
intersections_left = sjoin(gdf1, gdf2, how="inner", predicate='intersects')
intersections_right = sjoin(gdf2, gdf1, how="inner", predicate='intersects')

# Trouver les index de gdf1 et gdf2 qui ne figurent pas dans les résultats de la jointure spatiale
non_intersected_indexes_gdf1 = set(gdf1.index) - set(intersections_left.index)
non_intersected_indexes_gdf2 = set(gdf2.index) - set(intersections_right.index)  # Utiliser index_right pour les intersections à partir de gdf2

# Convertir les ensembles d'indices en listes
non_intersected_indexes_gdf1_list = list(non_intersected_indexes_gdf1)
non_intersected_indexes_gdf2_list = list(non_intersected_indexes_gdf2)

# Filtrer gdf1 et gdf2 pour conserver uniquement les polygones non intersectés
suppression = gdf1.loc[non_intersected_indexes_gdf1_list]
creation = gdf2.loc[non_intersected_indexes_gdf2_list]

suppression.to_file("suppression_mayotte_2020_2023.gpkg", driver='GPKG')
creation.to_file("creation_mayotte_2020_2023.gpkg", driver='GPKG')